version: '3'
services: 
    web:
        build: ./docker/php
        depends_on: 
            - mysql
        ports:
            - '8000:80'
        volumes: 
            - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - .:/var/www/html
            - ./logs:/var/log/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            - LANG=ja_JA.UTF-8

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
  mysql-data: